# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(920, 680)
        Dialog.setStyleSheet("background-color: #808080")
        self.pwd = QtWidgets.QLineEdit(Dialog)
        self.pwd.setGeometry(QtCore.QRect(340, 360, 211, 31))
        self.pwd.setStyleSheet("background-color: #C0C0C0")
        self.pwd.setObjectName("pwd")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(340, 290, 211, 31))
        self.email.setStyleSheet("background-color: #C0C0C0")
        self.email.setObjectName("email")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(340, 270, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(340, 340, 61, 20))
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QPushButton(Dialog)
        self.login.setGeometry(QtCore.QRect(470, 400, 75, 23))
        self.login.setObjectName("login")
        self.logup = QtWidgets.QPushButton(Dialog)
        self.logup.setGeometry(QtCore.QRect(350, 400, 75, 23))
        self.logup.setObjectName("logup")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "email"))
        self.label_2.setText(_translate("Dialog", "password"))
        self.login.setText(_translate("Dialog", "Войти"))
        self.logup.setText(_translate("Dialog", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
