# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(920, 680)
        font = QtGui.QFont()
        font.setItalic(True)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: #EAEAEA;")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(280, 140, 351, 351))
        self.frame.setStyleSheet("border-radius: 30px;\n"
"background-color: #FFFFFF")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(70, 90, 211, 41))
        self.email.setStyleSheet("border-radius: 10px;background-color: #EAEAEA;")
        self.email.setObjectName("email")
        self.logup = QtWidgets.QPushButton(self.frame)
        self.logup.setGeometry(QtCore.QRect(210, 280, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        self.logup.setFont(font)
        self.logup.setStyleSheet("color: #1B76FF")
        self.logup.setObjectName("logup")
        self.login = QtWidgets.QPushButton(self.frame)
        self.login.setGeometry(QtCore.QRect(70, 230, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        self.login.setFont(font)
        self.login.setToolTipDuration(-1)
        self.login.setStyleSheet("border-radius: 10px;background-color: #5099F2;color : #FFFFFF")
        self.login.setObjectName("login")
        self.pwd = QtWidgets.QLineEdit(self.frame)
        self.pwd.setGeometry(QtCore.QRect(70, 140, 211, 41))
        self.pwd.setStyleSheet("border-radius: 10px;background-color: #EAEAEA")
        self.pwd.setObjectName("pwd")
        self.help = QtWidgets.QPushButton(self.frame)
        self.help.setGeometry(QtCore.QRect(130, 190, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.help.setFont(font)
        self.help.setStyleSheet("color: #BABABA")
        self.help.setObjectName("help")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 280, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.no = QtWidgets.QFrame(self.frame)
        self.no.setGeometry(QtCore.QRect(260, 153, 16, 16))
        self.no.setStyleSheet("background-color: #FF0000;border-radius: 8px;")
        self.no.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.no.setFrameShadow(QtWidgets.QFrame.Raised)
        self.no.setObjectName("no")
        self.email.raise_()
        self.login.raise_()
        self.logup.raise_()
        self.pwd.raise_()
        self.help.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.no.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.logup.setText(_translate("Dialog", "Sign up"))
        self.login.setText(_translate("Dialog", "Войти"))
        self.help.setText(_translate("Dialog", "forgot your password?"))
        self.label.setText(_translate("Dialog", "Sign in"))
        self.label_2.setText(_translate("Dialog", "don\'t have an account?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
