# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(920, 680)
        Dialog.setStyleSheet("background-color: #808080")
        self.main = QtWidgets.QPushButton(Dialog)
        self.main.setGeometry(QtCore.QRect(0, 0, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.main.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/ramil/.designer/img/free-icon-star-126482.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main.setIcon(icon)
        self.main.setObjectName("main")
        self.activity = QtWidgets.QPushButton(Dialog)
        self.activity.setGeometry(QtCore.QRect(190, 0, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.activity.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/ramil/.designer/img/free-icon-musical-note-126493.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activity.setIcon(icon1)
        self.activity.setObjectName("activity")
        self.conf = QtWidgets.QPushButton(Dialog)
        self.conf.setGeometry(QtCore.QRect(380, 0, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.conf.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/ramil/.designer/img/free-icon-pie-chart-126484.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.conf.setIcon(icon2)
        self.conf.setObjectName("conf")
        self.users = QtWidgets.QPushButton(Dialog)
        self.users.setGeometry(QtCore.QRect(570, 0, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.users.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/ramil/.designer/img/free-icon-avatar-126486.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.users.setIcon(icon3)
        self.users.setObjectName("users")
        self.setin = QtWidgets.QPushButton(Dialog)
        self.setin.setGeometry(QtCore.QRect(760, 0, 161, 81))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        self.setin.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/ramil/.designer/img/free-icon-settings-126472.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setin.setIcon(icon4)
        self.setin.setObjectName("setin")
        self.activity_2 = QtWidgets.QFrame(Dialog)
        self.activity_2.setGeometry(QtCore.QRect(20, 150, 431, 501))
        self.activity_2.setStyleSheet("background-color: #C0C0C0")
        self.activity_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.activity_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.activity_2.setObjectName("activity_2")
        self.project = QtWidgets.QFrame(Dialog)
        self.project.setGeometry(QtCore.QRect(500, 150, 401, 131))
        self.project.setStyleSheet("background-color: #C0C0C0")
        self.project.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.project.setFrameShadow(QtWidgets.QFrame.Raised)
        self.project.setObjectName("project")
        self.info = QtWidgets.QFrame(Dialog)
        self.info.setGeometry(QtCore.QRect(500, 310, 401, 341))
        self.info.setStyleSheet("background-color: #C0C0C0")
        self.info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info.setObjectName("info")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.main.setText(_translate("Dialog", "Главная"))
        self.activity.setText(_translate("Dialog", "Создание мероприятий"))
        self.conf.setText(_translate("Dialog", "конференц-зал"))
        self.users.setText(_translate("Dialog", "Пользователи"))
        self.setin.setText(_translate("Dialog", "Настройки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
