# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(484, 383)
        Dialog.setStyleSheet("border-radius: 30px;\n"
"background-color: #FFFFFF")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(130, 60, 211, 41))
        self.name.setStyleSheet("border-radius: 10px;background-color: #EAEAEA")
        self.name.setText("")
        self.name.setObjectName("name")
        self.push = QtWidgets.QPushButton(Dialog)
        self.push.setGeometry(QtCore.QRect(130, 320, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        font.setWeight(50)
        self.push.setFont(font)
        self.push.setToolTipDuration(-1)
        self.push.setStyleSheet("border-radius: 10px;background-color: #5099F2;color : #FFFFFF")
        self.push.setObjectName("push")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(220, 280, 110, 26))
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setDate(QtCore.QDate(2021, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 285, 67, 17))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(130, 130, 211, 141))
        self.textEdit.setStyleSheet("border-radius: 10px;background-color: #EAEAEA")
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 110, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: red;")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "new task"))
        self.push.setText(_translate("Dialog", "push"))
        self.label_2.setText(_translate("Dialog", "Deadline"))
        self.label_3.setText(_translate("Dialog", "not found"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
